/** @typedef {import('@/types/accounting').CategoryId} CategoryId */

export const accountingCopy = {
  appName: '清简记账',
  tabs: {
    home: '首页',
    details: '明细',
    statistics: '统计',
    profile: '我的',
  },
  actions: {
    addEntry: '新增一笔',
    accounts: '账户',
    categories: '分类',
    syncNow: '立即同步',
    expand: '展开更多',
    collapse: '收起',
    save: '保存修改',
    edit: '编辑',
    delete: '删除',
    create: '新增一笔',
    backToDetails: '返回明细',
    retrySync: '重试同步',
  },
  home: {
    balanceLabel: '本月结余',
    recentTransactions: '最近记录',
    accountsSubtitleSuffix: '个账户',
    transactionSubtitleSuffix: '条记录',
    updatedPrefix: '最近更新',
    emptyTitle: '还没有记录',
    emptyDescription: '先记上一笔，这个月的账本就开始动起来了。',
  },
  details: {
    monthRecordSuffix: '条记录',
    emptyTitle: '这个月还没有记录',
    emptyDescription: '切换月份，或先记上一笔。',
  },
  statistics: {
    title: '统计',
    subtitleSuffix: '条记录',
    balanceLabel: '本月结余',
    emptyTitle: '还没有统计数据',
    emptyDescription: '先记上几笔，这个月的统计就会慢慢出现。',
    expenseSectionTitle: '支出分类',
    incomeSectionTitle: '收入分类',
    expenseEmpty: '这个月还没有支出记录。',
    incomeEmpty: '这个月还没有收入记录。',
    percentSuffix: '占比',
  },
  profile: {
    title: '我的',
    subtitle: '账本、账户和同步状态',
    ledger: '账本',
    email: '邮箱',
    currency: '币种',
    timeZone: '时区',
    defaultAccount: '默认账户',
    activeAccounts: '启用账户',
    mockMode: '当前模式',
    mockModeValue: '仅本地 Mock 数据',
    workspace: '工作区',
    accounts: '账户',
    syncStatus: '同步状态',
    syncPendingSuffix: '条待同步',
    syncFailedSuffix: '条同步失败',
    syncUpdatedPrefix: '最近更新',
    allSynced: '全部变更已同步',
  },
  form: {
    type: '类型',
    amount: '金额',
    category: '分类',
    account: '账户',
    dateTime: '时间',
    note: '备注',
    notePlaceholder: '补充一点说明',
    syncStatus: '同步状态',
    amountPlaceholder: '0.00',
    dateTimePlaceholder: 'YYYY-MM-DDTHH:mm',
    saving: '保存中...',
    notFoundTitle: '这笔记录找不到了',
    notFoundDescription: '它可能已经被删除，或当前 Mock 数据已经重置。',
    errors: {
      amount: '请输入大于 0 的金额',
      category: '请选择分类',
      account: '请选择账户',
      dateTime: '请输入正确的时间，格式为 YYYY-MM-DDTHH:mm',
    },
  },
  entryType: {
    expense: '支出',
    income: '收入',
  },
  syncStatus: {
    pending: '待同步',
    synced: '已同步',
    failed: '同步失败',
  },
  accountTypes: {
    cash: '现金',
    bank: '银行卡',
    alipay: '支付宝',
    wechat: '微信',
  },
  transactionNotes: {
    lunch: '午饭',
    salary: '五月工资',
    subway: '通勤地铁',
    groceries: '周末采购',
    coffee: '咖啡',
    freelance: '项目尾款',
  },
};

/** @type {Record<CategoryId, string>} */
export const accountingCategoryLabels = {
  'cat-food': '餐饮',
  'cat-commute': '通勤',
  'cat-groceries': '日用采购',
  'cat-coffee': '咖啡茶饮',
  'cat-salary': '工资',
  'cat-freelance': '副业',
};

/** @type {Record<string, string>} */
export const accountingMonthLabels = {
  '2026-05': '2026年5月',
  '2026-04': '2026年4月',
};
